// <auto-generated />
using System;
using DataVortex.LicenseServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataVortex.LicenseServer.Migrations
{
    [DbContext(typeof(LicenseDbContext))]
    [Migration("20260726021802_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DataVortex.LicenseServer.Activation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ActivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LeaseExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LicenseId");

                    b.ToTable("Activations");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotpSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.AuthLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("AuthLogs");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FingerprintHash");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FingerprintTolerancePercent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxActivations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FingerprintHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastRefreshAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LicenseId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.SigningKeyRecord", b =>
                {
                    b.Property<string>("Kid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyPkcs8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeySpki")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Kid");

                    b.ToTable("SigningKeys");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.Activation", b =>
                {
                    b.HasOne("DataVortex.LicenseServer.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataVortex.LicenseServer.License", "License")
                        .WithMany("Activations")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("License");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.License", b =>
                {
                    b.HasOne("DataVortex.LicenseServer.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.Session", b =>
                {
                    b.HasOne("DataVortex.LicenseServer.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("DataVortex.LicenseServer.License", b =>
                {
                    b.Navigation("Activations");
                });
#pragma warning restore 612, 618
        }
    }
}
